default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  user: postgres
  password:
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: uhura

test:
  <<: *default
  database: uhura_test
